/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 服务正常 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 控制台登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登录成功，返回 JWT */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前账号（按 JWT sub 查库；仅 JWT，改名后旧 token 返回 401） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 账号信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            account?: components["schemas"]["Account"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改密码（校验当前密码；新密码 ≥ 6 字符；已有 JWT 不失效） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已修改 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改用户名（校验当前密码；UNIQUE 查重；旧 token 的 sub 随即失效） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已修改（返回新用户名） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            username?: string;
                        };
                    };
                };
                400: components["responses"]["Error"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/cert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent 提交 CSR 换 mTLS 证书（token 放 body，无需 JWT） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        token: string;
                        csr_pem: string;
                    };
                };
            };
            responses: {
                /** @description 签发成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            cert_pem?: string;
                            ca_cert_pem?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出主机（附在线状态 + 最后心跳 + 超时标记；支持 tag 过滤与分页） */
        get: {
            parameters: {
                query?: {
                    tag?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 主机列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            hosts?: components["schemas"]["HostView"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建主机 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateHost"];
                };
            };
            responses: {
                /** @description 创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            host?: components["schemas"]["Host"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        get?: never;
        /** 更新主机 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["HostId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateHost"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            host?: components["schemas"]["Host"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /** 删除主机（软删除） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["HostId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["HostId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设置主机标签 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["HostId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tags: string[];
                    };
                };
            };
            responses: {
                /** @description 设置成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            host?: components["schemas"]["Host"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出已注册 Agent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent 列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            agents?: components["schemas"]["Agent"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proxies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出活跃的 SOCKS5 代理 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 代理列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            proxies?: components["schemas"]["ProxyView"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 为 agent 开启 SOCKS5 代理（Server 本地监听，流量经 agent 出站） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        /**
                         * @description SOCKS5 监听地址
                         * @default 127.0.0.1:1080
                         */
                        listen_addr?: string;
                    };
                };
            };
            responses: {
                /** @description 代理已开启 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProxyView"];
                    };
                };
                400: components["responses"]["InvalidArgument"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proxies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 停止并移除 SOCKS5 代理 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已停止 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-gen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出 Agent 现场编译生成任务 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 生成任务列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            jobs?: components["schemas"]["AgentGenJob"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建 Agent 生成任务（现场交叉编译，异步执行） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAgentGen"];
                };
            };
            responses: {
                /** @description 任务已创建（status=compiling，轮询 GET /agent-gen/{id} 取进度） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentGenJob"];
                    };
                };
                400: components["responses"]["InvalidArgument"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-gen/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 查询生成任务进度（含编译日志尾部） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 任务详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentGenJob"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-gen/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 下载编译完成的 Agent 二进制（任务就绪后可用） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 二进制文件流（application/octet-stream 附件下载） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        /** 查询 Agent 详情（附在线状态） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AgentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent 详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            agent?: components["schemas"]["AgentDetail"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** 注销 Agent（删 agent 行 + 孤儿主机软删） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AgentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 注销成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get?: never;
        /** 更新 Agent 关联主机的标签 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AgentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        tags: string[];
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            host?: components["schemas"]["Host"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}/uninstall": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 下发卸载指令（SelfDestruct，可选删除二进制） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AgentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @default true */
                        remove_binary?: boolean;
                    };
                };
            };
            responses: {
                /** @description 指令已下发 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                409: components["responses"]["NotConnected"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}/terminal": {
        parameters: {
            query: {
                /** @description JWT（WebSocket 握手无法带 Authorization header） */
                token: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        /** 交互式会话终端（WebSocket，二进制帧双向流转） */
        get: {
            parameters: {
                query: {
                    /** @description JWT（WebSocket 握手无法带 Authorization header） */
                    token: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["AgentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebSocket 升级成功 */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 下发命令执行 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        command: string;
                        args?: string[];
                    };
                };
            };
            responses: {
                /** @description 返回 job_id */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            job_id?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出 Job */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job 列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            jobs?: components["schemas"]["Job"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** 查询单个 Job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job 详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            job?: components["schemas"]["Job"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}/stream": {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Job 输出实时流（WebSocket，二进制帧为输出增量） */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebSocket 升级成功 */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询指标（时序） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 指标列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            metrics?: components["schemas"]["Metric"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 指标实时流（WebSocket，二进制帧为 JSON 指标点） */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebSocket 升级成功 */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 通知实时流（WebSocket，二进制帧为 JSON 通知；决策 009 系统内通知） */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebSocket 升级成功 */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传文件到 Agent */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        local_path: string;
                        remote_path: string;
                    };
                };
            };
            responses: {
                /** @description 上传完成（含 SHA256 校验结果） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            checksum_ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从 Agent 下载文件 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        remote_path: string;
                        local_path: string;
                    };
                };
            };
            responses: {
                /** @description 下载完成（含 SHA256 校验结果） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            checksum_ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 列目录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        path: string;
                    };
                };
            };
            responses: {
                /** @description 目录条目 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            path?: string;
                            entries?: components["schemas"]["FileEntry"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/script": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 下发脚本任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        script: string;
                    };
                };
            };
            responses: {
                /** @description 任务已创建 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建定时任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        command: string;
                        args?: string[];
                        interval_secs: number;
                    };
                };
            };
            responses: {
                /** @description 定时任务已创建 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forward/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 正向连接执行（Server 拨号 Agent） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 按主机名解析（conn_mode=forward） */
                        hostname?: string;
                        /** @description 直接拨号地址 host:port */
                        agent_addr?: string;
                        command: string;
                        args?: string[];
                    };
                };
            };
            responses: {
                /** @description 执行结果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listeners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出监听器 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 监听器列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            listeners?: components["schemas"]["Listener"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建监听器（默认 stopped） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateListener"];
                };
            };
            responses: {
                /** @description 创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            listener?: components["schemas"]["Listener"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listeners/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ListenerId"];
            };
            cookie?: never;
        };
        get?: never;
        /** 更新监听器 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ListenerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateListener"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            listener?: components["schemas"]["Listener"];
                        };
                    };
                };
            };
        };
        post?: never;
        /** 删除监听器 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ListenerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listeners/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ListenerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启动监听器（动态绑定 gRPC） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ListenerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 启动成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/listeners/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ListenerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 停止监听器 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ListenerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 停止成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出服务 */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 服务列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            services?: components["schemas"]["Service"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建常驻服务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateService"];
                };
            };
            responses: {
                /** @description 创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            service?: components["schemas"]["Service"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** 更新服务 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ServiceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateService"];
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            service?: components["schemas"]["Service"];
                        };
                    };
                };
            };
        };
        post?: never;
        /** 删除服务（running 状态需先 stop） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ServiceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 删除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启动服务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ServiceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 启动成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 停止服务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ServiceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 停止成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重启服务（stop + start） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ServiceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 重启成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        /** 查询服务日志（快照） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ServiceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 日志内容 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            log?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{id}/logs/stream": {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["ServiceId"];
            };
            cookie?: never;
        };
        /** 服务日志实时流（WebSocket，二进制帧为日志增量） */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path: {
                    id: components["parameters"]["ServiceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebSocket 升级成功 */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 列出 Agent 进程 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                    };
                };
            };
            responses: {
                /** @description 进程列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            processes?: components["schemas"]["ProcessInfo"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processes/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 杀进程（不存在返回 ok=false，仍 200） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        pid: number;
                    };
                };
            };
            responses: {
                /** @description 结果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/net/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 采集 Agent 网络信息（接口 + TCP/UDP 连接表） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                    };
                };
            };
            responses: {
                /** @description 网络信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            hostname?: string;
                            interfaces?: components["schemas"]["NetInterface"][];
                            connections?: components["schemas"]["NetConnection"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sys-services/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 枚举目标机系统服务（Windows Service / systemd / launchctl） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                    };
                };
            };
            responses: {
                /** @description 系统服务列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            services?: components["schemas"]["SysService"][];
                            error?: string | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sys-services/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 系统服务操作（start / stop / restart） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agent_id: string;
                        /** @description 服务标识（服务名 / unit 名 / label） */
                        name: string;
                        /** @enum {string} */
                        action: "start" | "stop" | "restart";
                    };
                };
            };
            responses: {
                /** @description 操作结果 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name?: string;
                            action?: string;
                            ok?: boolean;
                            error?: string | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出审计日志 */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 审计记录 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            audit?: components["schemas"]["Audit"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出告警 */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 告警列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            alerts?: components["schemas"]["Alert"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出系统内通知（上线/下线/预警小卡片，决策 009） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    /** @description 只看未读（"true" / "1"） */
                    unread?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 通知列表（按时间倒序） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            notifications?: components["schemas"]["Notification"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 未读通知数（小卡片红点） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 未读数 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            count?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 标记单条通知已读 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["HostId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已标记 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                /** @description 通知不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 全部通知标记已读 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已标记 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updated?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页列出 API key（仅 JWT；只回展示前缀，不含哈希/明文） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API key 列表（按创建时间倒序） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            api_keys?: components["schemas"]["ApiKey"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建 API key（仅 JWT；明文 key 仅本次响应返回一次） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /**
                         * Format: date-time
                         * @description RFC 3339 过期时间，空则永不过期
                         */
                        expires_at?: string;
                    };
                };
            };
            responses: {
                /** @description 创建成功（key 为明文，仅此一次） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            api_key?: components["schemas"]["ApiKey"];
                            /** @example helm_3f9a... */
                            key?: string;
                        };
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ApiKeyId"];
            };
            cookie?: never;
        };
        /** API key 详情（仅 JWT） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ApiKeyId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 详情 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            api_key?: components["schemas"]["ApiKey"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** 吊销 API key（仅 JWT；幂等，已吊销仍返回 ok） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ApiKeyId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已吊销 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载运维 skill 完整包（zip；JWT / API key 均可，决策 011） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description zip 包（内嵌 SKILL.md + scripts/ + references/） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skill/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill 包清单（版本 + 文件 + sha256，用于升级对比） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 包清单 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name?: string;
                            version?: string;
                            file_count?: number;
                            files?: {
                                path?: string;
                                size?: number;
                                sha256?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Host: {
            /** Format: uuid */
            id?: string;
            hostname?: string;
            os?: string;
            arch?: string;
            platform?: string;
            tags?: string[];
            /** @enum {string} */
            conn_mode?: "reverse" | "forward";
            addr?: string;
            /** @description Server 看到的 Agent 连接源地址（外网视角） */
            public_ip?: string;
            /** @description Agent 注册上报的本机网卡地址（内网视角，IPv4 在前） */
            local_ips?: string[];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        HostView: components["schemas"]["Host"] & {
            online?: boolean;
            /** Format: date-time */
            last_seen?: string | null;
            stale?: boolean;
            /** @description 关联 Agent 标识（最近注册的一个） */
            agent_id?: string | null;
            agent_version?: string | null;
        };
        CreateHost: {
            hostname: string;
            /**
             * @default reverse
             * @enum {string}
             */
            conn_mode: "reverse" | "forward";
            addr?: string;
            tags?: string[];
        };
        UpdateHost: {
            hostname: string;
            /** @enum {string} */
            conn_mode?: "reverse" | "forward";
            addr?: string;
            tags?: string[];
            os?: string;
            arch?: string;
            platform?: string;
        };
        Agent: {
            id?: string;
            /** Format: uuid */
            host_id?: string;
            version?: string;
            hostname?: string;
            /** Format: date-time */
            last_heartbeat_at?: string | null;
        };
        CreateAgentGen: {
            /** @enum {string} */
            os: "windows" | "linux" | "macos";
            /** @enum {string} */
            arch: "x86_64" | "aarch64";
            /**
             * Format: uuid
             * @description 监听器（决定烙入的连入地址与注册 token）
             */
            listener_id: string;
            /**
             * @description reverse=Agent 主动连 Server；forward=Agent 监听、Server 拨号
             * @default reverse
             * @enum {string}
             */
            conn_mode: "reverse" | "forward";
            /** @description forward 模式监听地址（默认 0.0.0.0:50052） */
            listen_addr?: string;
            /** @description 覆盖连入地址（reverse 模式有效；留空由监听器地址推导，通配主机替换为服务器内网 IP） */
            server_addr?: string;
        };
        AgentGenJob: {
            /** Format: uuid */
            id?: string;
            os?: string;
            arch?: string;
            /** @description Rust 目标三元组 */
            triple?: string;
            /** @description 烙入的 Server gRPC 地址 */
            server_addr?: string;
            /** @enum {string} */
            conn_mode?: "reverse" | "forward";
            /** @description forward 模式监听地址 */
            listen_addr?: string;
            /** @enum {string} */
            status?: "compiling" | "ready" | "failed";
            error?: string | null;
            file_size?: number | null;
            /** Format: date-time */
            created_at?: string;
            /** @description 编译日志尾部（详情查询返回，列表为空） */
            log_tail?: string[];
        };
        AgentDetail: components["schemas"]["Agent"] & {
            online?: boolean;
        };
        Job: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            task_id?: string | null;
            /** Format: uuid */
            host_id?: string;
            status?: string;
            command?: string;
            args?: string[];
            output?: string | null;
            exit_code?: number | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
        };
        Metric: {
            /** Format: uuid */
            host_id?: string;
            name?: string;
            value?: number;
            labels?: {
                [key: string]: string;
            };
            /** Format: date-time */
            ts?: string;
        };
        FileEntry: {
            name?: string;
            is_dir?: boolean;
            size?: number;
            modified_unix_ms?: number;
            mode?: string;
        };
        Listener: {
            /** Format: uuid */
            id?: string;
            name?: string;
            addr?: string;
            /** @enum {string} */
            proto?: "grpc";
            /** @enum {string} */
            status?: "running" | "stopped";
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateListener: {
            name: string;
            addr: string;
            /**
             * @default grpc
             * @enum {string}
             */
            proto: "grpc";
            auth?: string;
        };
        UpdateListener: {
            name: string;
            addr: string;
            /** @enum {string} */
            proto?: "grpc";
            auth?: string;
        };
        Service: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            host_id?: string;
            name?: string;
            command?: string;
            args?: string[];
            /** @enum {string} */
            status?: "running" | "stopped" | "failed";
            /** @enum {string} */
            restart_policy?: "no" | "always";
            pid?: number | null;
            exit_code?: number | null;
            log?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateService: {
            agent_id: string;
            name: string;
            command: string;
            args?: string[];
            /**
             * @default no
             * @enum {string}
             */
            restart_policy: "no" | "always";
        };
        UpdateService: {
            name: string;
            command: string;
            args?: string[];
            /** @enum {string} */
            restart_policy?: "no" | "always";
        };
        ProcessInfo: {
            pid?: number;
            name?: string;
            cpu_percent?: number;
            mem_bytes?: number;
            virt_mem_bytes?: number;
            parent_pid?: number;
            status?: string;
            user?: string;
            start_time_unix?: number;
            exe_path?: string;
            cmd?: string;
        };
        NetInterface: {
            name?: string;
            addrs?: string[];
            mac?: string;
            /** @description up / down / ... */
            status?: string;
            gateway?: string;
            /** @description ethernet / wifi / loopback / tunnel / other */
            kind?: string;
        };
        NetConnection: {
            /** @enum {string} */
            protocol?: "tcp" | "udp";
            local?: string;
            remote?: string;
            state?: string;
            pid?: number;
            process_name?: string;
        };
        ProxyView: {
            /** Format: uuid */
            id?: string;
            agent_id?: string;
            listen_addr?: string;
            /** @enum {string} */
            status?: "running";
        };
        SysService: {
            name?: string;
            display_name?: string;
            status?: string;
            start_type?: string;
            pid?: number;
            description?: string;
        };
        Audit: {
            /** Format: uuid */
            id?: string;
            actor?: string;
            action?: string;
            resource?: string;
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
        };
        Alert: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            host_id?: string;
            metric_name?: string;
            threshold?: number;
            value?: number;
            level?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Notification: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            host_id?: string;
            /** @enum {string} */
            kind?: "online" | "offline" | "alert";
            message?: string;
            read?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description API key 视图（不含哈希；明文仅创建响应返回一次） */
        ApiKey: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @example helm_3f9a81c2 */
            prefix?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        Account: {
            username?: string;
            /** @enum {string} */
            role?: "admin" | "operator";
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: {
        /** @description 错误 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: {
                        code?: string;
                        message?: string;
                    };
                };
            };
        };
        /** @description 未授权 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: Record<string, never>;
                };
            };
        };
        /** @description 请求参数不合法 */
        InvalidArgument: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: Record<string, never>;
                };
            };
        };
        /** @description 未找到 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: Record<string, never>;
                };
            };
        };
        /** @description Agent 离线 */
        NotConnected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: Record<string, never>;
                };
            };
        };
    };
    parameters: {
        HostId: string;
        AgentId: string;
        JobId: string;
        ListenerId: string;
        ServiceId: string;
        ApiKeyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
