[package]
name = "helm-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "helm-server"
path = "src/main.rs"

[lib]
name = "helm_server"
path = "src/lib.rs"

[dependencies]
helm-proto = { path = "../proto" }
tokio.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
axum.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-stream.workspace = true
sqlx.workspace = true
uuid.workspace = true
chrono.workspace = true
bcrypt.workspace = true
jsonwebtoken.workspace = true
sha2.workspace = true
hex.workspace = true
