/** MCP 工具编目（前端静态镜像，与 server/src/application/mcp_registry.rs OPS 注册表同步；SCOPES 同模式）。由 scripts/gen_mcp_catalog.py 生成——勿手改。 */
export interface McpOp {
  name: string;
  scope: string;
  os: string;
  method: string;
  path: string;
  summary: string;
  params: [string, string][];
}
export interface McpDomainGroup {
  domain: string;
  ops: McpOp[];
}
export const MCP_CATALOG: McpDomainGroup[] = [
  {
    domain: "host",
    ops: [
      {
        name: "exec.run",
        scope: "exec",
        os: "Any",
        method: "POST",
        path: "/api/v1/exec",
        summary: "在目标机执行命令（异步 job，返回 job_id 后用 jobs.get 取结果）",
        params: [["agent_id", "agent_id"], ["command", "命令"], ["args", "参数数组（可选）"]] as [string, string][],
      },
      {
        name: "exec.batch",
        scope: "exec",
        os: "Any",
        method: "POST",
        path: "/api/v1/exec/batch",
        summary: "多主机批量执行同一命令",
        params: [["agent_ids", "agent_id 数组"], ["command", "命令"], ["args", "参数数组（可选）"]] as [string, string][],
      },
      {
        name: "jobs.get",
        scope: "exec",
        os: "Any",
        method: "GET",
        path: "/api/v1/jobs/{id}",
        summary: "查询 job 状态与输出",
        params: [["id", "job_id"]] as [string, string][],
      },
      {
        name: "jobs.list",
        scope: "exec",
        os: "Any",
        method: "GET",
        path: "/api/v1/jobs",
        summary: "job 列表",
        params: [["page", "页码（可选）"], ["limit", "条数（可选）"]] as [string, string][],
      },
      {
        name: "tasks.script",
        scope: "exec",
        os: "Any",
        method: "POST",
        path: "/api/v1/tasks/script",
        summary: "跑一段脚本（--sh 或 --ps 封装）",
        params: [["agent_id", "agent_id"], ["command", "解释器（如 sh/bash/powershell）"], ["args", "参数数组"]] as [string, string][],
      },
      {
        name: "tasks.schedule",
        scope: "exec",
        os: "Any",
        method: "POST",
        path: "/api/v1/tasks/schedule",
        summary: "创建定时任务（按间隔重复执行）",
        params: [["agent_id", "agent_id"], ["command", "命令"], ["args", "参数数组"], ["interval_secs", "间隔秒数"]] as [string, string][],
      },
      {
        name: "forward.exec",
        scope: "forward",
        os: "Any",
        method: "POST",
        path: "/api/v1/forward/exec",
        summary: "正向连接执行（Server 主动拨号 agent）",
        params: [["hostname", "主机名或 agent_addr"], ["command", "命令"], ["args", "参数数组（可选）"]] as [string, string][],
      },
      {
        name: "files.upload",
        scope: "files",
        os: "Any",
        method: "POST",
        path: "/api/v1/files/upload",
        summary: "从 Server 侧上传文件到目标机",
        params: [["agent_id", "agent_id"], ["local_path", "Server 上的源路径"], ["remote_path", "目标机路径"]] as [string, string][],
      },
      {
        name: "files.download",
        scope: "files",
        os: "Any",
        method: "POST",
        path: "/api/v1/files/download",
        summary: "从目标机下载文件到 Server 侧",
        params: [["agent_id", "agent_id"], ["remote_path", "目标机路径"], ["local_path", "Server 上的落路径"]] as [string, string][],
      },
      {
        name: "files.list",
        scope: "files",
        os: "Any",
        method: "POST",
        path: "/api/v1/files/list",
        summary: "列目标机目录",
        params: [["agent_id", "agent_id"], ["path", "目录路径"]] as [string, string][],
      },
      {
        name: "sys_services.list",
        scope: "services",
        os: "Any",
        method: "POST",
        path: "/api/v1/sys-services/list",
        summary: "系统服务发现（Windows SCM / systemd / launchctl）",
        params: [["agent_id", "agent_id"]] as [string, string][],
      },
      {
        name: "sys_services.action",
        scope: "services",
        os: "Any",
        method: "POST",
        path: "/api/v1/sys-services/action",
        summary: "系统服务 start/stop/restart（需权限）",
        params: [["agent_id", "agent_id"], ["name", "服务名/unit 名"], ["action", "start|stop|restart"]] as [string, string][],
      },
      {
        name: "services.list",
        scope: "services",
        os: "Any",
        method: "GET",
        path: "/api/v1/services",
        summary: "平台托管常驻服务列表",
        params: [] as [string, string][],
      },
      {
        name: "services.create",
        scope: "services",
        os: "Any",
        method: "POST",
        path: "/api/v1/services",
        summary: "创建平台托管常驻服务",
        params: [["agent_id", "agent_id"], ["name", "服务名"], ["command", "命令"], ["args", "参数（可选）"], ["restart_policy", "重启策略（可选）"]] as [string, string][],
      },
      {
        name: "services.action",
        scope: "services",
        os: "Any",
        method: "POST",
        path: "/api/v1/services/{id}/{action}",
        summary: "托管服务 start/stop/restart",
        params: [["id", "服务 uuid"], ["action", "start|stop|restart"]] as [string, string][],
      },
      {
        name: "services.logs",
        scope: "services",
        os: "Any",
        method: "GET",
        path: "/api/v1/services/{id}/logs",
        summary: "托管服务日志快照",
        params: [["id", "服务 uuid"]] as [string, string][],
      },
      {
        name: "services.delete",
        scope: "services",
        os: "Any",
        method: "DELETE",
        path: "/api/v1/services/{id}",
        summary: "删除托管服务（破坏性）",
        params: [["id", "服务 uuid"]] as [string, string][],
      },
      {
        name: "processes.list",
        scope: "processes",
        os: "Any",
        method: "POST",
        path: "/api/v1/processes/list",
        summary: "进程列表（Linux 含内核线程）",
        params: [["agent_id", "agent_id"]] as [string, string][],
      },
      {
        name: "processes.kill",
        scope: "processes",
        os: "Any",
        method: "POST",
        path: "/api/v1/processes/kill",
        summary: "结束进程（破坏性）",
        params: [["agent_id", "agent_id"], ["pid", "进程号"]] as [string, string][],
      },
      {
        name: "net.info",
        scope: "processes",
        os: "Any",
        method: "POST",
        path: "/api/v1/net/info",
        summary: "网络信息（网卡 + 连接表）",
        params: [["agent_id", "agent_id"]] as [string, string][],
      },
      {
        name: "ir.scan",
        scope: "ir",
        os: "Windows",
        method: "POST",
        path: "/api/v1/ir/scan",
        summary: "自启动项全景扫描（Autoruns 12 分类 + 签名校验）",
        params: [["agent_id", "agent_id"], ["types", "扫描类型数组（可选，空=全部）"]] as [string, string][],
      },
      {
        name: "ir.autorun_action",
        scope: "ir",
        os: "Windows",
        method: "POST",
        path: "/api/v1/ir/autorun-action",
        summary: "自启动项 禁用/启用/删除（破坏性）",
        params: [["agent_id", "agent_id"], ["action", "disable|enable|delete"], ["key", "op_key（来自 ir.scan 结果）"]] as [string, string][],
      },
      {
        name: "ir.memscan_start",
        scope: "ir",
        os: "Windows",
        method: "POST",
        path: "/api/v1/ir/memscan/stream",
        summary: "启动流式内存扫描任务",
        params: [["agent_id", "agent_id"], ["pid", "进程号，0=全进程"], ["keyword", "匹配字符串"], ["min_len", "最小长度（可选）"]] as [string, string][],
      },
      {
        name: "ir.fs_timeline",
        scope: "ir",
        os: "Windows",
        method: "POST",
        path: "/api/v1/ir/fs-timeline",
        summary: "NTFS USN 文件活动时间线",
        params: [["agent_id", "agent_id"], ["drive", "盘符（如 C）"], ["since_hours", "近 N 小时（可选）"], ["keyword", "文件名过滤（可选）"]] as [string, string][],
      },
      {
        name: "ir.evidence",
        scope: "ir",
        os: "Windows",
        method: "POST",
        path: "/api/v1/ir/evidence",
        summary: "一键证据包（进程/网络/服务/自启动/日志 JSON）",
        params: [["agent_id", "agent_id"]] as [string, string][],
      },
      {
        name: "ir.snapshots_save",
        scope: "ir",
        os: "Windows",
        method: "POST",
        path: "/api/v1/ir/snapshots",
        summary: "保存自启动项基线快照",
        params: [["agent_id", "agent_id"], ["name", "快照名"]] as [string, string][],
      },
      {
        name: "ir.snapshots_list",
        scope: "ir",
        os: "Windows",
        method: "GET",
        path: "/api/v1/ir/snapshots",
        summary: "快照列表",
        params: [] as [string, string][],
      },
      {
        name: "ir.snapshots_compare",
        scope: "ir",
        os: "Windows",
        method: "POST",
        path: "/api/v1/ir/snapshots/compare",
        summary: "与基线快照对比，diff 出新增/移除项",
        params: [["id", "基线快照 uuid"], ["agent_id", "agent_id"]] as [string, string][],
      },
    ],
  },
  {
    domain: "platform",
    ops: [
      {
        name: "hosts.list",
        scope: "hosts",
        os: "Any",
        method: "GET",
        path: "/api/v1/hosts",
        summary: "主机列表（含在线状态/系统版本/标签）",
        params: [["page", "页码，默认 1"], ["limit", "每页条数，默认 20"], ["tag", "按标签过滤（可选）"]] as [string, string][],
      },
      {
        name: "agent.tags",
        scope: "hosts",
        os: "Any",
        method: "PUT",
        path: "/api/v1/agents/{id}/tags",
        summary: "给 agent 打标签",
        params: [["id", "agent_id"], ["tags", "标签数组"]] as [string, string][],
      },
      {
        name: "agent.deregister",
        scope: "hosts",
        os: "Any",
        method: "DELETE",
        path: "/api/v1/agents/{id}",
        summary: "注销 agent（删档案；破坏性）",
        params: [["id", "agent_id"]] as [string, string][],
      },
      {
        name: "agent.uninstall",
        scope: "hosts",
        os: "Any",
        method: "POST",
        path: "/api/v1/agents/{id}/uninstall",
        summary: "卸载 agent（下发自毁指令；破坏性）",
        params: [["id", "agent_id"], ["remove_binary", "是否删除目标机上的二进制，默认 false"]] as [string, string][],
      },
      {
        name: "listeners.list",
        scope: "listeners",
        os: "Any",
        method: "GET",
        path: "/api/v1/listeners",
        summary: "gRPC 监听器列表",
        params: [] as [string, string][],
      },
      {
        name: "listeners.create",
        scope: "listeners",
        os: "Any",
        method: "POST",
        path: "/api/v1/listeners",
        summary: "创建 gRPC 监听器",
        params: [["name", "名称"], ["addr", "监听地址（如 0.0.0.0:50051）"], ["proto", "协议，grpc"]] as [string, string][],
      },
      {
        name: "listeners.action",
        scope: "listeners",
        os: "Any",
        method: "POST",
        path: "/api/v1/listeners/{id}/{action}",
        summary: "监听器 start/stop",
        params: [["id", "监听器 uuid"], ["action", "start|stop"]] as [string, string][],
      },
      {
        name: "listeners.delete",
        scope: "listeners",
        os: "Any",
        method: "DELETE",
        path: "/api/v1/listeners/{id}",
        summary: "删除监听器（破坏性）",
        params: [["id", "监听器 uuid"]] as [string, string][],
      },
      {
        name: "proxies.list",
        scope: "proxy",
        os: "Any",
        method: "GET",
        path: "/api/v1/proxies",
        summary: "活跃 SOCKS5 代理列表",
        params: [] as [string, string][],
      },
      {
        name: "proxies.create",
        scope: "proxy",
        os: "Any",
        method: "POST",
        path: "/api/v1/proxies",
        summary: "为 agent 开 SOCKS5 代理（Server 本地监听，流量经 agent 出站）",
        params: [["agent_id", "agent_id"], ["listen_addr", "Server 侧监听地址，默认 127.0.0.1:1080"]] as [string, string][],
      },
      {
        name: "proxies.stop",
        scope: "proxy",
        os: "Any",
        method: "DELETE",
        path: "/api/v1/proxies/{id}",
        summary: "停止代理",
        params: [["id", "代理 uuid"]] as [string, string][],
      },
      {
        name: "agent_gen.create",
        scope: "agent-gen",
        os: "Any",
        method: "POST",
        path: "/api/v1/agent-gen",
        summary: "创建 agent 现场编译任务（异步，用 agent_gen.status 轮询）",
        params: [["os", "windows|linux|macos"], ["arch", "x86_64|aarch64"], ["listener_id", "监听器 uuid"], ["conn_mode", "reverse|forward"], ["server_addr", "烙入地址（可选）"]] as [string, string][],
      },
      {
        name: "agent_gen.status",
        scope: "agent-gen",
        os: "Any",
        method: "GET",
        path: "/api/v1/agent-gen/{id}",
        summary: "查询编译任务状态与日志尾",
        params: [["id", "任务 uuid"]] as [string, string][],
      },
    ],
  },
];

/** op 总数（与 check_docs 的 MCP op 对账口径一致）。 */
export const MCP_OP_COUNT = MCP_CATALOG.reduce((n, d) => n + d.ops.length, 0); // 41
